Add DiBit Implementation
anee769/bitvec pull request #2
Opened 2022-10-20 11:13 UTC by anee769

# **DiBit Implementation**
- An implementation for a Bit Vector of size 2.
- It can accept n number of responses.
- The responses are stored in an uint64 slice according to the indices.
### Functionalities
- `Set` method sets a given state at given index.
- `Unset` method unsets the state for a given index.
- `Has` method checks whether the state at a given index matches the given state.
- `State` method returns the state at a given index.
- `String` method displays the **DiBit** as a string.
- `MaxState` method returns the maximum state value for **DiBit**.

2022-10-26 14:45 UTC, munna0908 requested changes
Good Work 👏, Minor changes required.

2022-10-30 17:37 UTC, munna0908 approved these changes
@anee769 LGTM, Please accommodate changes suggested by @manishmeganathan

2022-11-01 15:48 UTC, manishmeganathan approved these changes

2022-11-01 15:52 UTC, merged

2022-11-02 06:16 UTC, munna0908 reviewed
LGTM 👏